---
- name: Install Drupal and Drush with MariaDB, Nginx, and PHP-FPM
  hosts: all
  strategy: debug
  remote_user: vagrant
  sudo: yes

  vars:
    vagrant_ip: 192.168.88.88
    vagrant_memory: 1024
    sites:
      drupal8.axai.org:
        git: "http://git.drupal.org/project/drupal.git"
        version: 8.1.x
        # use ssl
        #ssl: yes
        # use this if the site has aliases (so we can redirect)
        #aliases: ["www.drupal8.axai.org"]
        # use this if you want this to be the default_server in nginx
        #default: yes
    dbs:
      drupal8:
        dbuser: drupal8
        dbpass: test
        dbhost: localhost

  roles:
    - { role: mysql , tags: [mysql] }

 
